### PR TITLE
Fire an event when the image is loaded, add some custom css properties

### PR DESCRIPTION
**Pull request by nmunrod2l**
Adding custom properties for `border-radius` and `object-fit` on the `img`.

Added an event when the image is loaded so I can know when to hide my skeleton.

### CODE REVIEW

**Comment by jstefaniuk-d2l** [comment]
Watch out for `object-fit` if you need ie11 support, since I don't think it works there

**Comment by jstefaniuk-d2l** [comment]
https://caniuse.com/#feat=object-fit

**Comment by nmunrod2l** [comment]
For my use case, I think we're okay with things not looking perfect on IE11.

**Comment by nmunrod2l** [comment]
Does CI not work on forks?

**Comment by jstefaniuk-d2l** [comment]
Hmm that's been a problem with some of the repos in the past, maybe try it on a branch?

**Comment by nmunrod2l** [comment]
I don't have permission to create a branch in this repo.

**Comment by jstefaniuk-d2l** [comment]
Try again

**Pull request closed without merging**
